"""所有工具的统一导出"""

from .tools_file import READ_TOOL, WRITE_TOOL, EDIT_TOOL, GLOB_TOOL, GREP_TOOL
from .tools_shell_web import BASH_TOOL, WEB_FETCH_TOOL, WEB_SEARCH_TOOL
from .tools_agent_task import (
    TASK_TOOL, ASK_USER_TOOL, TASK_CREATE_TOOL, TASK_UPDATE_TOOL,
    TASK_LIST_TOOL, TASK_GET_TOOL, TASK_OUTPUT_TOOL, TASK_STOP_TOOL
)
from .tools_mcp import MCP_LIST_TOOL, MCP_READ_TOOL, MCP_CALL_TOOL
from .tools_notebook_skill_lsp import (
    NOTEBOOK_EDIT_TOOL, SKILL_TOOL, SKILL_DISCOVER_TOOL,
    LSP_DIAGNOSTICS_TOOL, LSP_EXECUTE_TOOL
)
from .tools_workflow_config import (
    ENTER_PLAN_TOOL, EXIT_PLAN_TOOL, ENTER_WORKTREE_TOOL, EXIT_WORKTREE_TOOL,
    CONFIG_GET_TOOL, CONFIG_SET_TOOL, TOOL_SEARCH_TOOL,
    SLEEP_TOOL, SEND_MESSAGE_TOOL, TODO_WRITE_TOOL,
    TEAM_CREATE_TOOL, TEAM_DELETE_TOOL, REMOTE_TRIGGER_TOOL
)


BUILTIN_TOOLS = [
    # 文件 (5)
    READ_TOOL, WRITE_TOOL, EDIT_TOOL, GLOB_TOOL, GREP_TOOL,
    # Shell & Web (3)
    BASH_TOOL, WEB_FETCH_TOOL, WEB_SEARCH_TOOL,
    # Agent & Task (8)
    TASK_TOOL, ASK_USER_TOOL, TASK_CREATE_TOOL, TASK_UPDATE_TOOL,
    TASK_LIST_TOOL, TASK_GET_TOOL, TASK_OUTPUT_TOOL, TASK_STOP_TOOL,
    # MCP (3)
    MCP_LIST_TOOL, MCP_READ_TOOL, MCP_CALL_TOOL,
    # Notebook, Skill, LSP (5)
    NOTEBOOK_EDIT_TOOL, SKILL_TOOL, SKILL_DISCOVER_TOOL,
    LSP_DIAGNOSTICS_TOOL, LSP_EXECUTE_TOOL,
    # Workflow (4)
    ENTER_PLAN_TOOL, EXIT_PLAN_TOOL, ENTER_WORKTREE_TOOL, EXIT_WORKTREE_TOOL,
    # Config (3)
    CONFIG_GET_TOOL, CONFIG_SET_TOOL, TOOL_SEARCH_TOOL,
    # Misc (3)
    SLEEP_TOOL, SEND_MESSAGE_TOOL, TODO_WRITE_TOOL,
    # Team (3)
    TEAM_CREATE_TOOL, TEAM_DELETE_TOOL, REMOTE_TRIGGER_TOOL,
]


def register_all_tools():
    """注册所有工具到全局注册表"""
    from .registry import get_registry
    registry = get_registry()
    for tool in BUILTIN_TOOLS:
        registry.register(tool)


__all__ = ["BUILTIN_TOOLS", "register_all_tools"]
