"""Legacy 0.x public API surface.

These names are kept through the 0.8 release line.  The 0.9 public API should
prefer ``loom.Agent`` with the shorter configuration vocabulary exported from
``loom`` and ``loom.config``.
"""

from __future__ import annotations

from ..agent import Agent, create_agent, tool
from ..config import (
    AgentConfig,
    FilesystemWatchMethod,
    GenerationConfig,
    HeartbeatConfig,
    HeartbeatInterruptPolicy,
    KnowledgeBundle,
    KnowledgeCitation,
    KnowledgeDocument,
    KnowledgeEvidence,
    KnowledgeEvidenceItem,
    KnowledgeQuery,
    KnowledgeResolver,
    KnowledgeSource,
    MemoryBackend,
    MemoryConfig,
    MemoryProvider,
    ModelRef,
    PolicyConfig,
    PolicyContext,
    ResourceThresholds,
    RuntimeConfig,
    RuntimeFallback,
    RuntimeFallbackMode,
    RuntimeFeatures,
    RuntimeLimits,
    SafetyEvaluator,
    SafetyRule,
    ToolAccessPolicy,
    ToolHandler,
    ToolParameterSpec,
    ToolPolicy,
    ToolRateLimitPolicy,
    ToolSpec,
    WatchConfig,
    WatchKind,
)

__all__ = [
    "Agent",
    "create_agent",
    "tool",
    "AgentConfig",
    "ModelRef",
    "GenerationConfig",
    "ToolParameterSpec",
    "ToolHandler",
    "ToolSpec",
    "ToolAccessPolicy",
    "ToolRateLimitPolicy",
    "ToolPolicy",
    "PolicyContext",
    "PolicyConfig",
    "MemoryBackend",
    "MemoryConfig",
    "MemoryProvider",
    "WatchKind",
    "FilesystemWatchMethod",
    "ResourceThresholds",
    "WatchConfig",
    "HeartbeatInterruptPolicy",
    "HeartbeatConfig",
    "RuntimeFallbackMode",
    "RuntimeFallback",
    "RuntimeLimits",
    "RuntimeFeatures",
    "RuntimeConfig",
    "SafetyEvaluator",
    "SafetyRule",
    "KnowledgeDocument",
    "KnowledgeQuery",
    "KnowledgeCitation",
    "KnowledgeEvidenceItem",
    "KnowledgeEvidence",
    "KnowledgeBundle",
    "KnowledgeResolver",
    "KnowledgeSource",
]
